# Reference: https://www.poornerd.com/2020/08/31/deploy-nextjs-github-actions.html
name: Parse Docstring

on:
  push:
    branches: [ main ]

jobs:
  parse-docstring:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.1.0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ../harvest
        pip install docstring-parser
    - name: Create tmp directory
      run: |
        mkdir tmp
    - name: Run parser
      run: |
        python parser.py
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./tmp